version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-taiko-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bokntwjxpqqc"
s3_prefix = "test-taiko-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
